title: i18n-tasks
description: Manage translation and localization with static analysis, for Ruby i18n
google_analytics: UA-65961090-1
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
